# Generated by Django 6.0.6 on 2026-07-02 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=255)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('mode', models.CharField(choices=[('rag', 'RAG 질의응답'), ('calculator', '법률 계산기'), ('news', '판례/법률 뉴스'), ('supervisor', '전문 상담사')], default='rag', max_length=20)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('feedback', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
