# Generated by Django 6.0.6 on 2026-07-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_prompttemplate_prompttemplateversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
