# Generated by Django 6.0.6 on 2026-07-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chathistory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='mode',
            field=models.CharField(choices=[('case_based_answer', '사례 기반 답변'), ('case_with_procedure', '사례 판단 + 절차 안내'), ('procedure_guidance', '절차 안내'), ('allowance_calculator', '수당 계산기'), ('latest_news', '최신 뉴스'), ('supervisor', '전문 상담사')], default='rag', max_length=20),
        ),
    ]
