# Generated by Django 6.0.6 on 2026-07-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calc_type', models.CharField(choices=[('retirement', '퇴직금'), ('severance', '해고예고수당'), ('annual', '연차수당'), ('severance_pay', '퇴직금'), ('weekly', '주휴수당'), ('overtime', '야근수당'), ('other', '기타 계산')], default='other', max_length=20)),
                ('input_data', models.JSONField(default=dict)),
                ('result_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'calculator_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
