# Generated by Django 6.0.6 on 2026-07-06 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalculatorHistory',
        ),
    ]
