# Generated by Django 6.0.6 on 2026-07-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMUsageLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('node_name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('call_type', models.CharField(default='llm', max_length=20)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'monitoring_llmusagelog',
            },
        ),
        migrations.CreateModel(
            name='NodeExecutionLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('node_name', models.CharField(max_length=100)),
                ('elapsed_ms', models.FloatField()),
                ('status', models.CharField(default='success', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'monitoring_nodeexecutionlog',
            },
        ),
        migrations.CreateModel(
            name='PriceConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100, unique=True)),
                ('prompt_token_price', models.FloatField()),
                ('completion_token_price', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(default='system', max_length=120)),
            ],
            options={
                'db_table': 'monitoring_priceconfig',
            },
        ),
    ]
